# Generated by Django 4.2.7 on 2023-11-29 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0002_serie_imagem_detalhes_alter_serie_imagem_thumb'),
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tipo_item', models.CharField(choices=[('Filme', 'Filme'), ('Serie', 'Serie')], max_length=50)),
                ('imagem_banner', models.ImageField(upload_to='banner')),
                ('ativo', models.BooleanField(default=False)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.serie')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
    ]
