# Generated by Django 4.2.7 on 2023-11-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercards',
            name='video',
        ),
        migrations.AddField(
            model_name='bannercards',
            name='filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
        migrations.AlterField(
            model_name='bannercards',
            name='imagem_banner',
            field=models.ImageField(upload_to='images_banners/banner'),
        ),
    ]
