# Generated by Django 4.2.7 on 2023-11-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
        ('series', '0002_serie_imagem_detalhes_alter_serie_imagem_thumb'),
        ('home', '0002_remove_bannercards_video_bannercards_filme_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerCards',
            new_name='Banner',
        ),
    ]
