# Generated by Django 4.2.7 on 2023-11-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_bannercards_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='ativo',
            new_name='active',
        ),
    ]
