# Generated by Django 4.2.7 on 2023-12-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Collections',
        ),
    ]
