# Generated by Django 4.2.7 on 2023-12-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_collection_collections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collections',
        ),
    ]
