# Generated by Django 4.2.7 on 2023-11-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=200)),
                ('imagem_thumb', models.ImageField(upload_to='images/thumb')),
                ('imagem_detalhe', models.ImageField(upload_to='images/detalhes')),
                ('sinopse', models.CharField(max_length=650)),
                ('tipo', models.CharField(default='filme', editable=False, max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('generos', models.ManyToManyField(to='series.genero')),
            ],
        ),
    ]
