# Generated by Django 4.2.7 on 2023-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='imagem_thumb',
            new_name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='imagem_detalhe',
        ),
        migrations.AddField(
            model_name='filme',
            name='image_detail',
            field=models.ImageField(default='', upload_to='images/detail'),
            preserve_default=False,
        ),
    ]
