# Generated by Django 4.2.7 on 2023-11-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_rename_imagem_thumb_filme_image_thumb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='ativo',
            new_name='active',
        ),
    ]
