# Generated by Django 4.2.7 on 2023-11-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_rename_ativo_filme_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='generos',
            new_name='genre',
        ),
    ]
