# Generated by Django 4.2.7 on 2023-11-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_rename_generos_filme_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='tipo',
            new_name='type',
        ),
    ]
