# Generated by Django 4.2.7 on 2023-11-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_rename_tipo_filme_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='nome_filme',
            new_name='name_movie',
        ),
    ]
