# Generated by Django 4.2.7 on 2023-12-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0008_alter_filme_collection_delete_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/filmes')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
    ]
