# Generated by Django 5.1.1 on 2024-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0009_filmevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmevideo',
            name='video',
        ),
        migrations.AddField(
            model_name='filme',
            name='hls_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='filmevideo',
            name='file',
            field=models.FileField(default=1, upload_to='videos/movies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='type',
            field=models.CharField(choices=[('desenho_filme', 'Desenho'), ('filme', 'Filme')], max_length=13),
        ),
    ]
