from home.views import home
from home.views import desenhos_all
from home.views import desenhos_series
from home.views import desenhos_filmes
from home.views import movies_series
from home.views import search_home
from home.views import movies_series_by_genero_home
from home.views import movies_by_genre
from home.views import collection_all
from home.views import series
from home.views import filmes
