# Generated by Django 4.2.7 on 2023-11-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_episodio', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['numero_episodio'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_serie', models.CharField(max_length=100)),
                ('imagem_thumb', models.ImageField(upload_to='images/detalhes')),
                ('categoria', models.CharField(max_length=150)),
                ('tipo', models.CharField(default='serie', editable=False, max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('generos', models.ManyToManyField(to='series.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/videos/series')),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.episodio')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.numerotemporada')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.serie')),
            ],
        ),
        migrations.AddField(
            model_name='episodio',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.temporada'),
        ),
    ]
