# Generated by Django 4.2.7 on 2023-11-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_imagem_detalhes_alter_serie_imagem_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='nome_serie',
            new_name='name_serie',
        ),
        migrations.AddField(
            model_name='serie',
            name='name_serie_portuguese',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
