# Generated by Django 4.2.7 on 2023-11-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_rename_nome_serie_serie_name_serie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='imagem_thumb',
            new_name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='imagem_detalhes',
        ),
        migrations.AddField(
            model_name='serie',
            name='image_detail',
            field=models.ImageField(default='', upload_to='images/detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/series'),
        ),
    ]
