# Generated by Django 4.2.7 on 2023-11-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_rename_categoria_serie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='name_serie_portuguese',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
