# Generated by Django 4.2.7 on 2023-11-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_alter_serie_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='category',
            new_name='collection',
        ),
    ]
