# Generated by Django 4.2.7 on 2023-11-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_rename_category_serie_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='generos',
            new_name='genre',
        ),
    ]
