# Generated by Django 4.2.7 on 2023-11-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_rename_generos_serie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='ativo',
            new_name='active',
        ),
    ]
