# Generated by Django 4.2.7 on 2023-11-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_rename_tipo_serie_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodio',
            options={'ordering': ['episode_number']},
        ),
        migrations.RenameField(
            model_name='episodio',
            old_name='numero_episodio',
            new_name='episode_number',
        ),
    ]
