# Generated by Django 4.2.7 on 2023-11-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0012_alter_episodio_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='titulo',
            new_name='episode_name',
        ),
    ]
