# Generated by Django 4.2.7 on 2023-11-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0013_rename_titulo_episodio_episode_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='temporada',
            new_name='season',
        ),
    ]
