# Generated by Django 4.2.7 on 2023-11-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0014_rename_temporada_episodio_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numerotemporada',
            old_name='numero',
            new_name='number',
        ),
    ]
