# Generated by Django 4.2.7 on 2023-11-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0015_rename_numero_numerotemporada_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporada',
            old_name='numero_temporada',
            new_name='season_number',
        ),
    ]
