# Generated by Django 4.2.7 on 2023-11-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0016_rename_numero_temporada_temporada_season_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='episodio',
            new_name='episode',
        ),
    ]
