# Generated by Django 4.2.7 on 2023-12-04 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0019_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.collections'),
        ),
    ]
