# Generated by Django 5.1.1 on 2024-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0020_serie_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='type',
            field=models.CharField(choices=[('desenho_serie', 'Desenho'), ('serie', 'Serie')], max_length=13),
        ),
    ]
